"""empty message

Revision ID: b217fafdb5f0
Revises: 1c667e62f698
Create Date: 2024-08-23 15:24:41.917447

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b217fafdb5f0'
down_revision: Union[str, None] = '1c667e62f698'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('attachments', sa.JSON(), nullable=True))
    op.add_column('thread', sa.Column('tool_resources', sa.JSON(), nullable=True))
    op.create_index('token_assistant_token_idx', 'token', ['assistant_token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('token_assistant_token_idx', table_name='token')
    op.drop_column('thread', 'tool_resources')
    op.drop_column('message', 'attachments')
    # ### end Alembic commands ###
