"""empty message

Revision ID: 6db192bc124b
Revises: 66734dc3664b
Create Date: 2024-01-18 17:17:53.932240

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '6db192bc124b'
down_revision: Union[str, None] = '66734dc3664b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('run', sa.Column('additional_instructions', sa.TEXT(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('run', 'additional_instructions')
    # ### end Alembic commands ###
