"""empty message

Revision ID: 66734dc3664b
Revises: 38c796c62e21
Create Date: 2024-01-07 17:46:55.736276

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '66734dc3664b'
down_revision: Union[str, None] = 'eacc2313d69c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('assistant', 'instructions',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('run', 'instructions',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('run', 'instructions',
               existing_type=sa.TEXT(),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('assistant', 'instructions',
               existing_type=sa.TEXT(),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
    # ### end Alembic commands ###
