"""empty message

Revision ID: 5b2b73d0fdf6
Revises: b217fafdb5f0
Create Date: 2024-11-15 18:30:43.391344

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '5b2b73d0fdf6'
down_revision: Union[str, None] = 'b217fafdb5f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('run', sa.Column('stream_options', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('run', 'stream_options')
    # ### end Alembic commands ###
